//
//  UpdateProgressInteractor.swift
//  Readify (Remake)
//
//  Created by Hafizh Mo on 07/09/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UpdateProgressBusinessLogic {
  func updateProgress(progress: String?)
  func completeGoal()
}

class UpdateProgressInteractor: UpdateProgressBusinessLogic {
  var presenter: UpdateProgressPresentationLogic?
  
  func updateProgress(progress: String?) {
    guard let progress = progress, let value = Int(progress) else {
      presenter?.presentUpdatedCallback(message: "Progress field still empty!")
      return
    }
    
    SharedPreference.saveInt(key: .progress, value: value)
    presenter?.presentUpdatedCallback(message: nil)
  }
  
  func completeGoal() {
    SharedPreference.saveString(key: .bookTitle, value: "")
    SharedPreference.saveInt(key: .totalPages, value: 0)
    SharedPreference.saveDouble(key: .timer, value: 0)
    
    presenter?.presentCompletedCallback()
  }
}
