//
//  UpdateProgressInteractor.swift
//  Readify (Remake)
//
//  Created by Hafizh Mo on 07/09/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UpdateProgressBusinessLogic {
  func updateProgress(progress: String?)
}

class UpdateProgressInteractor: UpdateProgressBusinessLogic {
  var presenter: UpdateProgressPresentationLogic?
  
  func updateProgress(progress: String?) {
    guard let progress = progress, let value = Int(progress), let goal = UserDefaults.standard.goal else {
      presenter?.presentUpdatedCallback(message: "Progress field still empty!")
      return
    }
    
    if value > goal.total {
      presenter?.presentUpdatedCallback(message: "There's only \(goal.total) pages")
      return
    }
    
    if value == goal.total {
      presenter?.presentCompleted()
      return
    }
    
    UserDefaults.standard.goal = Goal(title: goal.title, total: goal.total, timer: goal.timer, progress: value)
    presenter?.presentUpdatedCallback(message: nil)
  }
}
