//
//  UpdateProgressPresenter.swift
//  Readify (Remake)
//
//  Created by Hafizh Mo on 07/09/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UpdateProgressPresentationLogic {
  func presentUpdatedCallback(message: String?)
}

class UpdateProgressPresenter: UpdateProgressPresentationLogic {
  weak var viewController: UpdateProgressDisplayLogic?
  
  func presentUpdatedCallback(message: String?) {
    viewController?.displayUpdatedCallback(message: message)
  }
}
