//
//  CurrentGoalInteractor.swift
//  Readify (Remake)
//
//  Created by Hafizh Mo on 29/08/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Combine

protocol CurrentGoalBusinessLogic {
  func showGoal(request: CurrentGoal.ShowGoal.Request)
}

protocol CurrentGoalDataStore {}

class CurrentGoalInteractor: CurrentGoalBusinessLogic, CurrentGoalDataStore {
  var presenter: CurrentGoalPresentationLogic?
  var subscriber: AnyCancellable?
  
  func showGoal(request: CurrentGoal.ShowGoal.Request) {
    subscriber = UserDefaults.standard
      .publisher(for: \.goal)
      .sink() { [weak self] goal in
        guard let goal = goal else {
          self?.presenter?.presentPlaceholder()
          return
        }
        
        let response = CurrentGoal.ShowGoal.Response(title: goal.title, total: goal.total, progress: goal.progress)
        self?.presenter?.presentGoal(response: response)
      }
  }
}
