//
//  CurrentGoalPresenter.swift
//  Readify (Remake)
//
//  Created by Hafizh Mo on 29/08/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CurrentGoalPresentationLogic {
  func presentStreak(response: CurrentGoal.ShowStreak.Response)
  func presentGoal(response: CurrentGoal.ShowGoal.Response)
  func presentPlaceholder()
}

class CurrentGoalPresenter: CurrentGoalPresentationLogic {
  var viewController: CurrentGoalDisplayLogic?
  
  func presentGoal(response: CurrentGoal.ShowGoal.Response) {
    let title = response.title
    let progressStr = "\(response.progress)/\(response.total)"
    let percentage = Double(response.progress) / Double(response.total)
    let percentageStr = "\(Int(percentage * 100))%"
    
    let viewModel = CurrentGoal.ShowGoal.ViewModel(title: title, percentage: percentage, progressStr: progressStr, percentageStr: percentageStr)
    viewController?.displayGoal(viewModel: viewModel)
  }
  
  func presentPlaceholder() {
    viewController?.displayPlaceholder()
  }
  
  func presentStreak(response: CurrentGoal.ShowStreak.Response) {
    let dayAndWeek = "Day \(response.day) / Week \(response.week)"
    let viewModel = CurrentGoal.ShowStreak.ViewModel(dayAndWeek: dayAndWeek, items: response.items)
    viewController?.displayStreak(viewModel: viewModel)
  }
}
