//
//  CurrentGoalInteractor.swift
//  Readify (Remake)
//
//  Created by Hafizh Mo on 29/08/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CurrentGoalBusinessLogic {
  func showGoal(request: CurrentGoal.ShowGoal.Request)
}

protocol CurrentGoalDataStore {}

class CurrentGoalInteractor: CurrentGoalBusinessLogic, CurrentGoalDataStore {
  var presenter: CurrentGoalPresentationLogic?
  var worker: CurrentGoalWorker?
  
  func showGoal(request: CurrentGoal.ShowGoal.Request) {
    worker = CurrentGoalWorker()
    
    let response = CurrentGoal.ShowGoal.Response(title: worker?.getTitle(), total: worker?.getTotal(), progress: worker?.getProgress())
    presenter?.presentGoal(response: response)
  }
}
