//
//  CurrentGoalWorker.swift
//  Readify (Remake)
//
//  Created by Hafizh Mo on 29/08/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CurrentGoalWorker {
  func getTitle() -> String {
    return ""
  }
  
  func getProgress() -> Int {
    return 0
  }
  
  func getTotal() -> Int {
    return 0
  }
}
