//
//  CurrentGoalPresenter.swift
//  Readify (Remake)
//
//  Created by Hafizh Mo on 29/08/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CurrentGoalPresentationLogic {
  func presentGoal(response: CurrentGoal.ShowGoal.Response)
}

class CurrentGoalPresenter: CurrentGoalPresentationLogic {
  var viewController: CurrentGoalDisplayLogic?
  
  func presentGoal(response: CurrentGoal.ShowGoal.Response) {
    if let title = response.title, let progress = response.progress, let total = response.total {
      let percentage = Double(total / progress)
      let progressStr = "\(progress)/\(total)"
      
      let viewModel = CurrentGoal.ShowGoal.ViewModel(title: title, percentage: percentage, progressStr: progressStr)
      viewController?.displayGoal(viewModel: viewModel)
      
    } else {
      viewController?.displayPlaceholder()
    }
  }
}
