//
//  CompleteInteractor.swift
//  Readify (Remake)
//
//  Created by Hafizh Mo on 12/09/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CompleteBusinessLogic {
  func completeGoal()
}

class CompleteInteractor: CompleteBusinessLogic {
  var presenter: CompletePresentationLogic?
  
  func completeGoal() {
    UserDefaults.standard.goal = nil
    presenter?.presentCompleted()
  }
}
