//
//  FocusModeInteractor.swift
//  Readify (Remake)
//
//  Created by Hafizh Mo on 07/09/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FocusModeBusinessLogic {
  func prepareTimer()
}

class FocusModeInteractor: FocusModeBusinessLogic {
  var presenter: FocusModePresentationLogic?
  let focusModeWorker = FocusModeWorker()
  
  func prepareTimer() {
    guard let goal = UserDefaults.standard.goal else { return }
    
    let timerStr = focusModeWorker.formatTimer(s: Int(goal.timer))
    let response = FocusMode.Timer.Response(timer: timerStr, duration: Float(goal.timer))
    
    presenter?.presentTimer(response: response)
  }
}
