//
//  FocusModeWorker.swift
//  Readify (Remake)
//
//  Created by Hafizh Mo on 07/09/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class FocusModeWorker {
  func formatTimer(s: Int) -> String {
    let seconds = (s % 3600) % 60
    let minutes = s / 60
    let hours = s / 3600
    
    var timeString = ""
    if hours > 0 {
      timeString += String(format: "%02d", hours)
      timeString += ":"
    }
    timeString += String(format: "%02d", minutes)
    timeString += ":"
    timeString += String(format: "%02d", seconds)
    
    return timeString
  }
}
