//
//  CreateGoalModels.swift
//  Readify (Remake)
//
//  Created by Hafizh Mo on 03/09/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CreateGoal {
  
  enum PrepareGoal {
    struct Request {}
    
    struct Response {
      var title: String
      var total: Int
      var timer: Double
    }
    
    struct ViewModel {
      var title: String
      var total: String
      var timer: Double
    }
  }
  
  enum SaveGoal {
    struct Request {
      var title: String?
      var total: String?
      var timer: Double
    }
    
    struct Response {
      var isSuccess: Bool
      var message: String?
    }
    
    struct ViewModel {
      var isSuccess: Bool
      var message: String?
    }
  }
}
